// <auto-generated />
using System;
using HotelCodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelCodeFirst.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20240127221443_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelCodeFirst.Cargo", b =>
                {
                    b.Property<int>("CodCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCargo"));

                    b.Property<string>("NomeCargo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("CodCargo");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("HotelCodeFirst.Cliente", b =>
                {
                    b.Property<int>("CodCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCliente"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EnderecoCliente")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeCliente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("CodCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("HotelCodeFirst.Consumivel", b =>
                {
                    b.Property<int>("CodConsumivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodConsumivel"));

                    b.Property<string>("DescricaoConsumivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorConsumivel")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodConsumivel");

                    b.ToTable("Consumiveis");
                });

            modelBuilder.Entity("HotelCodeFirst.Consumo", b =>
                {
                    b.Property<int>("CodConsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodConsumo"));

                    b.Property<int?>("ConsumidoCodConsumivel")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHoraConsumido")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EntregueNoQuarto")
                        .HasColumnType("bit");

                    b.Property<int>("FkConsumiveisCodConsumivel")
                        .HasColumnType("int");

                    b.Property<int>("FkContaCodConta")
                        .HasColumnType("int");

                    b.HasKey("CodConsumo");

                    b.HasIndex("ConsumidoCodConsumivel");

                    b.HasIndex("FkContaCodConta");

                    b.ToTable("Consumo");
                });

            modelBuilder.Entity("HotelCodeFirst.Conta", b =>
                {
                    b.Property<int>("CodConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodConta"));

                    b.Property<int>("FkReservaCodReserva")
                        .HasColumnType("int");

                    b.HasKey("CodConta");

                    b.HasIndex("FkReservaCodReserva");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("HotelCodeFirst.Filial", b =>
                {
                    b.Property<int>("CodFilial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodFilial"));

                    b.Property<string>("EnderecoFilial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("Estrelas")
                        .HasColumnType("tinyint");

                    b.Property<string>("NomeFilial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("NumeroDeQuartos")
                        .HasColumnType("smallint");

                    b.HasKey("CodFilial");

                    b.ToTable("Filiais");
                });

            modelBuilder.Entity("HotelCodeFirst.FormaPagamento", b =>
                {
                    b.Property<int>("CodFormaPag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodFormaPag"));

                    b.Property<string>("FormaDePagamento")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CodFormaPag");

                    b.ToTable("FormasPagamento");
                });

            modelBuilder.Entity("HotelCodeFirst.Funcionario", b =>
                {
                    b.Property<int>("CodFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodFuncionario"));

                    b.Property<int>("FkCargoCodCargo")
                        .HasColumnType("int");

                    b.Property<string>("NomeFuncionario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodFuncionario");

                    b.HasIndex("FkCargoCodCargo");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("HotelCodeFirst.NotaFiscal", b =>
                {
                    b.Property<int>("CodNotaFiscal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodNotaFiscal"));

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkContaCodConta")
                        .HasColumnType("int");

                    b.Property<int>("FkFormasPagamentoCodFormaPag")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodNotaFiscal");

                    b.HasIndex("FkContaCodConta");

                    b.HasIndex("FkFormasPagamentoCodFormaPag");

                    b.ToTable("NotasFiscais");
                });

            modelBuilder.Entity("HotelCodeFirst.Quarto", b =>
                {
                    b.Property<int>("CodQuarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodQuarto"));

                    b.Property<bool>("Adaptavel")
                        .HasColumnType("bit");

                    b.Property<byte>("CapacidadeMax")
                        .HasColumnType("tinyint");

                    b.Property<int>("FkTiposQuartoCodTipoQuarto")
                        .HasColumnType("int");

                    b.Property<short>("NumeroQuarto")
                        .HasColumnType("smallint");

                    b.HasKey("CodQuarto");

                    b.HasIndex("FkTiposQuartoCodTipoQuarto");

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("HotelCodeFirst.Reserva", b =>
                {
                    b.Property<int>("CodReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodReserva"));

                    b.Property<bool>("Cancelada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ColchaoAdicional")
                        .HasColumnType("bit");

                    b.Property<int>("FkClientesCodCliente")
                        .HasColumnType("int");

                    b.Property<int>("FkFuncionariosCodFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("FkQuartosCodQuarto")
                        .HasColumnType("int");

                    b.HasKey("CodReserva");

                    b.HasIndex("FkClientesCodCliente");

                    b.HasIndex("FkFuncionariosCodFuncionario");

                    b.HasIndex("FkQuartosCodQuarto");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("HotelCodeFirst.ServLavPrestado", b =>
                {
                    b.Property<int>("CodServLavPrestado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodServLavPrestado"));

                    b.Property<int>("FKContaCodConta")
                        .HasColumnType("int");

                    b.Property<int>("FKServicosLavanderiaCodServLav")
                        .HasColumnType("int");

                    b.Property<int?>("ServicoCodServLav")
                        .HasColumnType("int");

                    b.HasKey("CodServLavPrestado");

                    b.HasIndex("FKContaCodConta");

                    b.HasIndex("ServicoCodServLav");

                    b.ToTable("ServLavPrestados");
                });

            modelBuilder.Entity("HotelCodeFirst.ServicoLavanderia", b =>
                {
                    b.Property<int>("CodServLav")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodServLav"));

                    b.Property<string>("DescricaoServLav")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorServLav")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodServLav");

                    b.ToTable("ServicosLavanderia");
                });

            modelBuilder.Entity("HotelCodeFirst.TipoQuarto", b =>
                {
                    b.Property<int>("CodTipoQuarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTipoQuarto"));

                    b.Property<string>("TipoDoQuarto")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CodTipoQuarto");

                    b.ToTable("TiposQuarto");
                });

            modelBuilder.Entity("HotelCodeFirst.Consumo", b =>
                {
                    b.HasOne("HotelCodeFirst.Consumivel", "Consumido")
                        .WithMany()
                        .HasForeignKey("ConsumidoCodConsumivel");

                    b.HasOne("HotelCodeFirst.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("FkContaCodConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumido");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("HotelCodeFirst.Conta", b =>
                {
                    b.HasOne("HotelCodeFirst.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("FkReservaCodReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("HotelCodeFirst.Funcionario", b =>
                {
                    b.HasOne("HotelCodeFirst.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("FkCargoCodCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("HotelCodeFirst.NotaFiscal", b =>
                {
                    b.HasOne("HotelCodeFirst.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("FkContaCodConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelCodeFirst.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FkFormasPagamentoCodFormaPag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("FormaPagamento");
                });

            modelBuilder.Entity("HotelCodeFirst.Quarto", b =>
                {
                    b.HasOne("HotelCodeFirst.TipoQuarto", "TipoQuarto")
                        .WithMany()
                        .HasForeignKey("FkTiposQuartoCodTipoQuarto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoQuarto");
                });

            modelBuilder.Entity("HotelCodeFirst.Reserva", b =>
                {
                    b.HasOne("HotelCodeFirst.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("FkClientesCodCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelCodeFirst.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FkFuncionariosCodFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelCodeFirst.Quarto", "Quarto")
                        .WithMany()
                        .HasForeignKey("FkQuartosCodQuarto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");

                    b.Navigation("Quarto");
                });

            modelBuilder.Entity("HotelCodeFirst.ServLavPrestado", b =>
                {
                    b.HasOne("HotelCodeFirst.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("FKContaCodConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelCodeFirst.ServicoLavanderia", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoCodServLav");

                    b.Navigation("Conta");

                    b.Navigation("Servico");
                });
#pragma warning restore 612, 618
        }
    }
}
